name: Push libs image.

on:
  workflow_dispatch:

jobs:
  libs:
    name: Build and push libraries image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone.
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: First set up.
        run: |
          sudo apt update
          curl -sSL https://install.python-poetry.org | python3 -
          cd Telegram/build/docker/centos_env
          poetry install
          DOCKERFILE=$(DEBUG= LTO= poetry run gen_dockerfile)
          echo "$DOCKERFILE" > Dockerfile
          rm -rf __pycache__

      - name: Free up some disk space.
        uses: jlumbroso/free-disk-space@ceedf095f4ec1a097402bc6bd80831f2e1a6fde6
        with:
          tool-cache: true

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v4

      - name: Libraries cache.
        uses: actions/cache@v6
        with:
          path: |
            ${{ runner.temp }}/.buildx-cache
            ${{ runner.temp }}/.mount-cache
          key: ${{ runner.OS }}-libs-${{ hashFiles('Telegram/build/docker/centos_env/**') }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Log in to GHCR.
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push libraries image.
        uses: docker/build-push-action@v7
        with:
          context: Telegram/build/docker/centos_env
          push: true
          tags: ghcr.io/archivetell/tdesktop-libs:latest
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Move cache.
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache{-new,}
